language: objective-c
osx_image: xcode9.2
rvm:
- 2.2         #see before_install for getting RVM stable.

env:
- PROJECT_NAME="Robot One" UNITY_PROJECT_PATH="src/app/Robot One"


cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

    
before_install:
- chmod a+x ./travis-scripts/*.sh

install:
- cat /etc/hosts
- ./travis-scripts/install.sh

script:
- ./travis-scripts/build.sh
# - ./travis-scripts/run-tests.sh

# after_success:
# - ./travis-scripts/export-unity-package.sh

# before_deploy:
# - DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"

# deploy:
#   provider: releases
#   api_key: $GITHUB_TOKEN
#   file: $DEPLOY_UNITYPACKAGE
#   skip_cleanup: true
#   overwrite: true
#   on:
#     tags: true 